### PR TITLE
Updates tests and help section

### PR DESCRIPTION
**Pull request by hqcasanova**
- Brings tests up to date.
- Rewrites the entire help section, using new screenshots, animated gifs and HTML instead of button captures.
- Reuses some of the old help text regarding features like links or contacts to expand the description above tables and lists and shows it also as a tooltip when adding a whole feature for the form.
- Improves icon-section relationship in the header.
- Updates config.json. It seems that there are two config.json files and the outdated version is being used in staging.

### CODE REVIEW

**Comment by hqcasanova** [comment]
@olgamelnichuk A couple of things:

* I have noticed there are two instances of the config.json file in the code:
  - Under the [root folder](https://github.com/EBIBioStudies/BioStudyUISub/commits/subm_templates/config.json).
  - Under [/src](https://github.com/EBIBioStudies/BioStudyUISub/commits/subm_templates/src/config.json).
Please note that the one under the root folder in the old_code_cleanup branch is outdated and should be the same as the one in src. It should also be updated in the code deployed to the staging environment. This may well be the source of some of exceptions.
Also note that these two versions of config.json exist since before I started.

* The styles on the deployed version are slightly off. I suspect something went wrong with the bundling of less files.

* One of the changes in this PR addresses another exception occurring when loading sent submissions: `TypeError Cannot read property 'hasOwnProperty' of undefined`. 

There are other exceptions. I'm working on identifying the source. Some of them seem to be related to the ahead-of-time compilation. If that is the case, I'd suggest to turn it off for now. That instance is not for production anyway.

All in all, the tool should be re-deployed at some point.

**Comment by olgamelnichuk** [comment]
* did you cleaned up the browser cache to update the styles?
* /api/submissions/<accno> returns submissions from the temporary storage, if submission is not temporary then it returns nothing..
* try to debug delete requests and see why it's ignored

**Comment by hqcasanova** [comment]
- As I explained above, it only happens with the help view. All other views show correctly with up-to-date styles. So, obviously, this is not your basic case of cached styles.
- As you already know, that same endpoint is used both for temporary and sent submissions. That has always been the case. In fact, the production version does use the same endpoint. If this is a change in the backend, I have not been notified and it is not the right time to make an API change.
- Obviously, I can't debug a backend issue beyond the browser. Also, you have access to the staging version so I would have thought you could do it yourself. I can only point you in the right direction and, as I stated above, the requests are ignored. Meaning that, when retrieving the list of sent submissions after deletion (request to `/api/submissions?submitted=false&offset=0&limit=15`), the list still includes the deleted submissions. Hence the use of the word "ignored".

**Comment by olgamelnichuk** [comment]
* fixed 9a144ca51164c1c826db0bb5889fb85d92ec14c5
* fixed 6f9de36668666224fc4f6cec843e5d67e285e0b2
* fixed 6f9de36668666224fc4f6cec843e5d67e285e0b2

**Comment by hqcasanova** [comment]
Great job. Thank you. There might be a new issue with submission requests... Still checking.

**Comment by olgamelnichuk** [comment]
Hmm.. I didn't change anything.. in pakage.json it is
```
    "@angular/common": "^4.3.0",
    "@angular/compiler": "^4.3.0",
    "@angular/compiler-cli": "^4.3.0",
    "@angular/core": "^4.3.0",
    "@angular/forms": "^4.3.0",
    "@angular/http": "^4.3.0",
    "@angular/platform-browser": "^4.3.0",
    "@angular/platform-browser-dynamic": "^4.3.0",
    "@angular/router": "^4.3.0"
```

**Comment by hqcasanova** [comment]
Interesting. That error (`ServerError: [200] [OK] Http failure during parsing for http://ves-hx-f2.ebi.ac.uk:8110/submissions/api/submissions/tmp/save`) didn't use to happen the first time you deployed. It only started to happen on the 1st of March. In any case, it seems reverting to the previous version is something along the lines of:
`npm install angular@4.3.6`
Source: https://stackoverflow.com/questions/37933922/how-to-install-older-version-of-typescript

**Comment by olgamelnichuk** [comment]
It means that the server response is not a json (e.g empty string).. I'll have a look at it. Thanks for letting me know.

**Comment by hqcasanova** [comment]
Actually, Juan and I did check that last week. In fact, that "save" endpoint has always come back with no response. You can test it yourself on production:
screen shot 2018-03-06 at 09 32 58
No, this has all the hallmarks of a change in behaviour on how Angular treats empty responses. In fact, if you look carefully, the error is an exception coming from Angular's native HTTP client. This didn't happen before: Angular would just happily not parse an empty response. The easiest solution is still to revert to version 4.3.6: `npm install angular@4.3.6`

**Pull request merged**
